sonata_admin:
    templates:
        layout:  SonataAdminBundle::extend_layout.html.twig
    dashboard:
        blocks:
            - { position: left, type: sonata.admin.block.admin_list, settings: { groups: [sonata.admin.group.content] }}
            - { position: right, type: sonata.admin.block.admin_list, settings: { groups: [sonata.admin.group.users, sonata.admin.group.administration.super] }}

        groups:
            sonata.admin.group.administration.super:
                label:           Super Administration
                label_catalogue: SonataAdminBundle
                icon:            '<i class="fa fa-globe"></i>'
                items:
                    - sonata.page.admin.site
                roles: [ ROLE_SUPER_ADMIN ]

            sonata.admin.group.users:
                label:           Gestion Utilisateurs
                label_catalogue: SonataAdminBundle
                icon:            '<i class="fa fa-group"></i>'
                items:
                    - sonata.user.admin.user
                    - sonata.user.admin.group
                roles: [ ROLE_ADMIN ]

            sonata.admin.group.content:
                label:           Contenus
    #                label_catalogue: SonataPageBundle
                icon:            '<i class="fa fa-sitemap"></i>'
                items:
                    - sonata.page.admin.page
                    - id4v_menu.admin.menu
                    - sonata.media.admin.media
                    - sonata.media.admin.gallery
                roles: [ ROLE_ADMIN ]
